Metrics/AbcSize:
  Max: 22

Metrics/BlockNesting:
  Max: 4

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 8

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false
